### ISSUE TITLE
uvloop 0.14.0

### ISSUE THREAD

**Issue by srkhost** [spumer/source-query-proxy#5]
Hello,

I get this error when I try to start it with python 3.5.5 and uvloop 0.14.0
Kernel: 
5.4.12-xanmod7 (on 4.19.0-6-amd64 its working)

Debian 10

It's working with uvloop 0.12.0

```
Traceback (most recent call last):
  File "daemon.py", line 572, in <module>
    _startup()
  File "daemon.py", line 568, in _startup
    loop.run_until_complete(asyncio.ensure_future(main()))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```
What can I do?

**Comment by spumer** [comment]
Should be fixed in 1.0.0 version

**Comment by srkhost** [comment]
Okay, thanks. I will check it, can I upgrade now?

**Comment by srkhost** [comment]
OK, so I uninstalled the previous version, and insalled the new one, and it says:
` [sqproxy] No one server to run. Please check config
`

**Comment by spumer** [comment]
Yes. sqproxy search config in two folders:

`/etc/sqproxy/conf.d/` and `./conf.d`
https://github.com/spumer/source-query-proxy/blob/master/source_query_proxy/config.py#L61

You can see [example](https://github.com/spumer/source-query-proxy/tree/master/examples/conf.d) of new configuration format

**Comment by spumer** [comment]
Previous JSON not supported anymore. You should migrate your config to YAML

**Comment by srkhost** [comment]
Hello,

so I have this error:
```
Traceback (most recent call last):
  File "redirect.py", line 11, in <module>
    from bcc import BPF
ImportError: cannot import name 'BPF' from 'bcc' (/usr/local/lib/python3.7/dist-packages/bcc/__init__.py)
2020-03-17 11:51:28,523 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code 1

```

http://prntscr.com/rhpcqr

I installed bcc-tools with apt and bcc with python (2,3) 

What can I do? :(

**Comment by spumer** [comment]
Post  `python3 -m pip freezee` here. But i guess you install https://pypi.org/project/bcc/ instead bcc-tools from https://github.com/iovisor/bcc/blob/master/INSTALL.md

**Comment by srkhost** [comment]
Yep, that was true I was installed the python bcc

Now I get this: https://pastebin.com/RE5iZVt0

Also there is my freeze:


```
asn1crypto==0.24.0
async-timeout==3.0.1
asyncio-dgram==1.0.1
attrs==19.3.0
backoff==1.10.0
bcc==0.8.0
bpf4==0.8.0
certifi==2018.8.24
chardet==3.0.4
click==7.1.1
cryptography==2.6.1
cycler==0.10.0
decorator==4.4.2
devscripts==2.19.5+deb10u1
entrypoints==0.3
gpg==1.12.0
idna==2.6
importlib-metadata==1.5.0
ipython-genutils==0.2.0
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.1.0
llvmlite==0.31.0
matplotlib==3.2.0
more-itertools==8.2.0
numba==0.48.0
numpy==1.18.1
packaging==20.3
pid==2.2.5
pluggy==0.13.1
py==1.8.1
pycrypto==2.6.1
pydantic==1.4
PyGObject==3.30.4
pylru==1.2.0
pyparsing==2.4.6
pyroute2==0.5.10
pytest==5.4.1
python-apt==1.8.4.1
python-dateutil==2.8.1
python-debian==0.1.35
python-dotenv==0.10.5
python-magic==0.4.16
pyxdg==0.25
PyYAML==5.3
requests==2.21.0
scipy==1.4.1
SecretStorage==2.3.1
six==1.12.0
source-query-proxy==1.0.0
speedtest-cli==2.1.2
traitlets==4.3.3
traittypes==0.2.1
unidiff==0.5.4
urllib3==1.24.1
uvloop==0.14.0
wcwidth==0.1.8
whatever==0.6
zipp==3.1.0

```

**Comment by spumer** [comment]
Which version of bcc you installed?

You can check it by command
`python -c 'import bcc; print(bcc.__version__)'`

**Comment by spumer** [comment]
Ou, i see.
bcc==0.8.0

You need >= 0.10.0. Please read `Upstream Stable and Signed Packages` section https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

This described in readme for eBPF part: https://github.com/spumer/source-query-proxy-kernel-module/tree/master/src-ebpf

**Comment by srkhost** [comment]
Yeah, I installed the BCC but it says that's the newest. (Debian 10)

**Comment by srkhost** [comment]
```
Ign:7 https://repo.iovisor.org/apt/buster buster InRelease
Err:8 https://repo.iovisor.org/apt/buster buster Release
  404  Not Found [IP: 104.199.116.191 443]
Reading package lists... Done
E: The repository 'https://repo.iovisor.org/apt/buster buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by srkhost** [comment]
```

asn1crypto==0.24.0
async-timeout==3.0.1
asyncio-dgram==1.0.1
attrs==19.3.0
backoff==1.10.0
bcc==0.10.0
bpf4==0.8.0
certifi==2018.8.24
chardet==3.0.4
click==7.1.1
cryptography==2.6.1
cycler==0.10.0
decorator==4.4.2
devscripts==2.19.5+deb10u1
entrypoints==0.3
gpg==1.12.0
idna==2.6
importlib-metadata==1.5.0
ipython-genutils==0.2.0
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.1.0
llvmlite==0.31.0
matplotlib==3.2.0
more-itertools==8.2.0
numba==0.48.0
numpy==1.18.1
packaging==20.3
pid==2.2.5
pluggy==0.13.1
py==1.8.1
pycrypto==2.6.1
pydantic==1.4
PyGObject==3.30.4
pylru==1.2.0
pyparsing==2.4.6
pyroute2==0.5.10
pytest==5.4.1
python-apt==1.8.4.1
python-dateutil==2.8.1
python-debian==0.1.35
python-dotenv==0.10.5
python-magic==0.4.16
pyxdg==0.25
PyYAML==5.3
requests==2.21.0
scipy==1.4.1
SecretStorage==2.3.1
six==1.12.0
source-query-proxy==1.0.0
speedtest-cli==2.1.2
traitlets==4.3.3
traittypes==0.2.1
unidiff==0.5.4
urllib3==1.24.1
uvloop==0.14.0
wcwidth==0.1.8
whatever==0.6
zipp==3.1.0

```

Again, same error.

**Comment by spumer** [comment]
Sorry, i see you use kernel 5.4. I think in your case we need 0.12.0 cause https://github.com/iovisor/bcc/releases/tag/v0.12.0

>  * Support for kernel up to 5.4

**Comment by srkhost** [comment]
```
python3 -c 'import bcc; print(bcc.__version__)'
0.12.0

```
executable: 'python3'
#!/usr/bin/python3
How do I force python3?

because I installed the 0.12.0 bcc, and same error 👯

**Comment by spumer** [comment]
Try to run `redirect.py` manually, without sqproxy.

**Comment by srkhost** [comment]
```
python3.8 -m pip freeze
attrs==19.3.0
bcc==0.1.10
decorator==4.4.2
ipython-genutils==0.2.0
llvmlite==0.31.0
more-itertools==8.2.0
numba==0.48.0
numpy==1.18.2
packaging==20.3
pluggy==0.13.1
py==1.8.1
pyparsing==2.4.6
pyroute2==0.5.10
pytest==5.4.1
six==1.14.0
traitlets==4.3.3
traittypes==0.2.1
wcwidth==0.1.8

```

I dont know really what I am doing now.

**Comment by spumer** [comment]
ok, let's go to Discord and after solve it publish solution here
spumer#8462

**Comment by spumer** [comment]
Solved by builing from sources.
I will try to pre-build bcc-tools for Python.
